### ISSUE TITLE
Bluetooth command failed

### ISSUE THREAD

**Issue by juliangkr** [Schnup89/ioBroker.eq3-Thermostat#13]
Hallo,

Vielen Dank für die Implementierung dieses Adapters!!

Ich habe deine Anleitung befolgt und dein Skript gibt am Ende korrekt die Möglichen Befehle aus. wenn ich aber mit getValue meine Thermostate auslesen will erhalte ich folgende Meldung:

```{sh}
Traceback (most recent call last):
  File "eq3Controller.py", line 13, in <module>
    thermostat.update()
  File "/home/pi/.local/lib/python3.7/site-packages/eq3bt/eq3btsmart.py", line 205, in update
    self._conn.make_request(PROP_WRITE_HANDLE, value)
  File "/home/pi/.local/lib/python3.7/site-packages/eq3bt/connection.py", line 73, in make_request
    self._conn.writeCharacteristic(handle, value, withResponse=with_response)
  File "/home/pi/.local/lib/python3.7/site-packages/bluepy/btle.py", line 543, in writeCharacteristic
    return self._getResp('wr')
  File "/home/pi/.local/lib/python3.7/site-packages/bluepy/btle.py", line 407, in _getResp
    resp = self._waitResp(wantType + ['ntfy', 'ind'], timeout)
  File "/home/pi/.local/lib/python3.7/site-packages/bluepy/btle.py", line 368, in _waitResp
    raise BTLEGattError("Bluetooth command failed", resp)
bluepy.btle.BTLEGattError: Bluetooth command failed (code: 14, error: Request attribute has encountered an unlikely error)
```

und iobroker findet das python Modul nicht:

```{sh}
ModuleNotFoundError: No module named 'eq3bt' 
```

Muss ich noch andere Dinge beachten?

**Comment by Schnup89** [comment]
Es scheint als würden die neueren Thermostate nicht mit der Bluetooth library funktionieren:

https://github.com/rytilahti/python-eq3bt/issues/41

Kannst du prüfen welche Version auf den Thermostaten läuft? Das sollte mit der Herstellerapp auslesbar seim

**Comment by Predator83** [comment]
Vielleicht hier noch mal querlesen, kam einiger neuer Input die letzten Tage 

https://github.com/rytilahti/python-eq3bt/issues/41

Bei Thermostaten mit der neuen Firmware muss wohl zuerst das Gerät (bspw. Raspi) mit dem Thermostat gepaired werden, sonst funktioniert die Kommunikation nicht. Eine Anleitung dazu ist in dem Link auch enthalten.

Das ist eigentlich ein Sicherheitsupdate hat aber den Nachteil, dass sich wohl nicht mehr mehrere verschiedene Geräte (bspw ein Handy und ein Raspi) mit einem Thermostat pairen lassen. 

Ich hab in der Hersteller App leider keine Möglichkeit gefunden die aktuelle Firmware Version auszulesen. Das könnte über die Bluetooth Library gehen aber dazu brauchst natürlich erst mal ne Verbindung ...

**Comment by ticarki** [comment]
Musste leider mein System abbauen, sobald ich es wieder am laufen habe melde ich mich.
