### ISSUE TITLE
GetValue-Command failed

### ISSUE THREAD

**Issue by Zaunkonig1** [Schnup89/ioBroker.eq3-Thermostat#17]
Servus zusammen,

ich habe den eq3Controller schon länger in Verwendung und steuere zwei eqiva-Thermostate (CC-RT-BLE-EQ) damit.

Seit ein paar Wochen allerdings, habe ich Fehlereinträge in der Log.

`eq3-thermostat.0	2021-02-14 09:55:49.760	error	bluepy.btle.BTLEDisconnectError: Failed to connect to peripheral 00:1A:22:17:02:F8, addr type: public
eq3-thermostat.0	2021-02-14 09:55:49.760	error	raise BTLEDisconnectError("Failed to connect to peripheral %s, addr type: %s" % (addr, addrType), rsp)
eq3-thermostat.0	2021-02-14 09:55:49.760	error	File "/home/iobroker/.local/lib/python3.5/site-packages/bluepy/btle.py", line 439, in _connect
eq3-thermostat.0	2021-02-14 09:55:49.760	error	self._connect(addr, addrType, iface)
eq3-thermostat.0	2021-02-14 09:55:49.760	error	File "/home/iobroker/.local/lib/python3.5/site-packages/bluepy/btle.py", line 445, in connect
eq3-thermostat.0	2021-02-14 09:55:49.760	error	self._conn.connect(self._mac)
eq3-thermostat.0	2021-02-14 09:55:49.760	error	File "/home/iobroker/.local/lib/python3.5/site-packages/eq3bt/connection.py", line 40, in __enter__
eq3-thermostat.0	2021-02-14 09:55:49.760	error	with self:
eq3-thermostat.0	2021-02-14 09:55:49.760	error	File "/home/iobroker/.local/lib/python3.5/site-packages/eq3bt/connection.py", line 71, in make_request
eq3-thermostat.0	2021-02-14 09:55:49.760	error	self._conn.make_request(PROP_WRITE_HANDLE, value)
eq3-thermostat.0	2021-02-14 09:55:49.760	error	File "/home/iobroker/.local/lib/python3.5/site-packages/eq3bt/eq3btsmart.py", line 205, in update
eq3-thermostat.0	2021-02-14 09:55:49.760	error	thermostat.update()
eq3-thermostat.0	2021-02-14 09:55:49.760	error	File "/home/pi/eq3Controller.py", line 13, in <module>
eq3-thermostat.0	2021-02-14 09:55:49.760	error	Traceback (most recent call last):
eq3-thermostat.0	2021-02-14 09:55:49.760	error	During handling of the above exception, another exception occurred:
eq3-thermostat.0	2021-02-14 09:55:49.760	error	bluepy.btle.BTLEDisconnectError: Failed to connect to peripheral 00:1A:22:17:02:F8, addr type: public
eq3-thermostat.0	2021-02-14 09:55:49.760	error	raise BTLEDisconnectError("Failed to connect to peripheral %s, addr type: %s" % (addr, addrType), rsp)
eq3-thermostat.0	2021-02-14 09:55:49.760	error	File "/home/iobroker/.local/lib/python3.5/site-packages/bluepy/btle.py", line 439, in _connect
eq3-thermostat.0	2021-02-14 09:55:49.760	error	self._connect(addr, addrType, iface)
eq3-thermostat.0	2021-02-14 09:55:49.760	error	File "/home/iobroker/.local/lib/python3.5/site-packages/bluepy/btle.py", line 445, in connect
eq3-thermostat.0	2021-02-14 09:55:49.760	error	self._conn.connect(self._mac)
eq3-thermostat.0	2021-02-14 09:55:49.760	error	File "/home/iobroker/.local/lib/python3.5/site-packages/eq3bt/connection.py", line 36, in __enter__
eq3-thermostat.0	2021-02-14 09:55:49.760	error	Traceback (most recent call last):
eq3-thermostat.0	2021-02-14 09:55:49.760	error	(816) -----------"Error: Command failed: python3 /home/pi/eq3Controller.py getValue 00:1A:22:17:02:F8
eq3-thermostat.0	2021-02-14 09:55:49.759	error	(816) Command "python3 /home/pi/eq3Controller.py getValue 00:1A:22:17:02:F8" failed!`

Als einen der ersten Schritte habe den Raspberry aktualisiert. --> Kein Erfolg
Adapter deinstalliert und wieder installiert --> Kein Erfolg
Der nächste Gedanke war, dass vielleicht mein Python veraltet ist. Also habe ich Python 3.9 installiert. --> Kein Erfolg.
Als nächstes versuchte ich die Thermostate neu zu pairen --> Kein Erfolg.

Das Verhalten ist sehr sonderbar. Das GetValue-Command funzt überhaupt nicht. Allerdings scheint das SetValue-Command zu 90% zu funzen. Leider auch nicht immer.
`eq3-thermostat.0	2021-02-14 10:00:20.242	info	(816) Command result: OK
eq3-thermostat.0	2021-02-14 10:00:16.591	info	(816) Set 21°C on Device 00:1A:22:16:A3:9E
eq3-thermostat.0	2021-02-14 10:00:16.589	info	(816) Command result: OK
eq3-thermostat.0	2021-02-14 10:00:11.046	info	(816) Set 21°C on Device 00:1A:22:17:02:F8
eq3-thermostat.0	2021-02-14 10:00:03.051	info	(816) eq3-thermostat.0.00:1A:22:16:A3:9E.temperature changed from system.adapter.javascript.0
eq3-thermostat.0	2021-02-14 10:00:03.044	info	(816) eq3-thermostat.0.00:1A:22:17:02:F8.temperature changed from system.adapter.javascript.0`

Was mir auch noch auffällt ist, obwohl ich `echo "alias python3=python3.9" >> ~/.bashrc` ausgeführt habe, zeigt sich in der LOG noch der Pfad zu Python3.5.

Ich hoffe ich habe mein Problem nicht zu verwirrend dargestellt. Und ich hoffe auch, dass mir vielleicht jemand einen Tipp geben kann, wie ich dies lösen und beseitigen kann.

Vielen Dank schon mal für eure unermüdliche Unterstützung.

Gruß Matthias

**Comment by Zaunkonig1** [comment]
Servus zusammen,

hat keiner ein kleine Idee?


Gruß Matthias

**Comment by DJTechMo** [comment]
@Zaunkonig1 
Hast du ein Firmware-Upgrade installiert bei den Thermostaten?

**Comment by Zaunkonig1** [comment]
Servus DJTechMo,

nein habe an den Thermostaten keine Veränderung vorgenommen. Außer einem Neustart.

**Comment by DJTechMo** [comment]
> Servus DJTechMo,
> 
> nein habe an den Thermostaten keine Veränderung vorgenommen. Außer einem Neustart.

Moin, hast du den BLE-Adapter installiert? Dieser verträgt sich bei mir nicht mit dem EQ3-Adapter. Ich denke beide nutzen die  Bluetooth-Sachen und behindern sich, bzw. behindert BLE das EQ3.

**Comment by derherrgraf** [comment]
#16 sollte das Problem beheben. Die Python Lib die hier hinter steht hat da etwas unschönes error handling
