### ISSUE TITLE
Probleme beim fetchen der Temperatur

### ISSUE THREAD

**Issue by derherrgraf** [Schnup89/ioBroker.eq3-Thermostat#6]
Nach einem update + upgrade gestern bekomme ich nun folgende Meldung im log und auch wenn ich es im Terminal von hand ausführe. Ich hab ein bisschen die Zugmaschine befragt, aber bin selbst auf keinen grünen Zweig gekommen.

```
pi@raspberrypi:~ $  python3 /home/pi/eq3Controller.py getValue MAC-ADRESSE
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/eq3bt/connection.py", line 36, in __enter__
    self._conn.connect(self._mac)
  File "/home/pi/.local/lib/python3.7/site-packages/bluepy/btle.py", line 445, in connect
    self._connect(addr, addrType, iface)
  File "/home/pi/.local/lib/python3.7/site-packages/bluepy/btle.py", line 439, in _connect
    raise BTLEDisconnectError("Failed to connect to peripheral %s, addr type: %s" % (addr, addrType), rsp)
bluepy.btle.BTLEDisconnectError: Failed to connect to peripheral MAC-ADRESSE, addr type: public

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/eq3Controller.py", line 16, in <module>
    thermostat.update()
  File "/home/pi/.local/lib/python3.7/site-packages/eq3bt/eq3btsmart.py", line 205, in update
    self._conn.make_request(PROP_WRITE_HANDLE, value)
  File "/home/pi/.local/lib/python3.7/site-packages/eq3bt/connection.py", line 71, in make_request
    with self:
  File "/home/pi/.local/lib/python3.7/site-packages/eq3bt/connection.py", line 40, in __enter__
    self._conn.connect(self._mac)
  File "/home/pi/.local/lib/python3.7/site-packages/bluepy/btle.py", line 445, in connect
    self._connect(addr, addrType, iface)
  File "/home/pi/.local/lib/python3.7/site-packages/bluepy/btle.py", line 439, in _connect
    raise BTLEDisconnectError("Failed to connect to peripheral %s, addr type: %s" % (addr, addrType), rsp)
bluepy.btle.BTLEDisconnectError: Failed to connect to peripheral MAC-ADRESSE, addr type: public
```

**Comment by derherrgraf** [comment]
Okay, der obligatorische Neustart hat das Problem gelöst, aber ich lass das mal offen, falls das weiter verfolgt werden soll.

**Comment by derherrgraf** [comment]
Wie in #7 beschrieben "spamt" das ganze inzwischen das ganze Log voll

**Comment by Schnup89** [comment]
Hi,
ich setze für die BT-Kommunikation mit den eq3's auf folgende Library (https://github.com/rytilahti/python-eq3bt).
Da das Errorhandling und das Verbindungshandling bei mehreren Verbindungen leider bei der Lib eingeschränkt ist, gibt es die erwähnten Fehlermeldungen.

Ein höherer Refresh-Intervall könnte hier Abhilfe schaffen, einfach mal testen.

Das Problem ist bekannt, um das zu lösen muss aber die Python-Library angepasst oder auf eine andere Python-Library gesetzt werden. Sobald ich wieder Zugriff einen Thermostat habe gehe ich das Thema an.

**Comment by derherrgraf** [comment]
ich werde das mal probieren in den nächsten Tagen :)

**Comment by ManuelW77** [comment]
Versuche es mal damit https://github.com/Schnup89/ioBroker.eq3-Thermostat/pull/16
